SELECT
    EXTRACT(YEAR FROM T2.SALES_DATE) YEAR,
    EXTRACT(MONTH FROM T2.SALES_DATE) MONTH,
    COUNT(DISTINCT T2.USER_ID) PUCHASED_USERS,
    ROUND(COUNT(DISTINCT T2.USER_ID) / 
          (SELECT
           COUNT (user_id) 
           FROM USER_INFO
           WHERE TO_CHAR(JOINED, 'YYYY-MM-DD' ) 
           BETWEEN '2021-01-01' AND '2021-12-31'), 1) PUCHASED_RATIO
FROM 
(
SELECT
    USER_ID
FROM USER_INFO
WHERE EXTRACT(YEAR FROM JOINED) = 2021
) T1, ONLINE_SALE T2 
WHERE T1.USER_ID = T2.USER_ID
GROUP BY EXTRACT(YEAR FROM T2.SALES_DATE), EXTRACT(MONTH FROM T2.SALES_DATE)
ORDER BY 1, 2
