-- 코드를 입력하세요
SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR,
       COUNT(TO_CHAR(DATETIME, 'HH24')) AS COUNT 
FROM ANIMAL_OUTS
GROUP BY TO_CHAR(DATETIME, 'HH24')
HAVING TO_CHAR(DATETIME, 'HH24') >= 9 AND TO_CHAR(DATETIME, 'HH24') <= 19
ORDER BY HOUR


-- 내가 풀었던 코드
SELECT TO_CHAR(DATETIME, 'HH24') AS HOUR,   -- datetime에서 시각을 추출하면서 char로 바꿨던 데이터 타입을 number로 다시 바꿔주지 않아서 계속 오답
       COUNT(TO_CHAR(DATETIME, 'HH24')) AS COUNT 
FROM ANIMAL_OUTS
GROUP BY TO_CHAR(DATETIME, 'HH24')
HAVING TO_CHAR(DATETIME, 'HH24') >= 9 AND TO_CHAR(DATETIME, 'HH24') <= 19
ORDER BY HOUR
